version: '3'
services:
  homehub:
    container_name: dl-homehub
    image: tesi
    volumes:
      - /home/simone/volume_tesi:/home/root/test_files
      - /home/simone/volume_tesi/lighttpd:/opt/lighttpd
      - /home/simone/volume_tesi/lighttpd_www/:/var/www
      - /home/simone/volume_tesi/lighttpd_ssl/:/var/ssl
      - /home/simone/volume_tesi/cgi-bin-src/:/cgi-bin-src
    command: /home/root/test_files/start.sh #telnetd -l /bin/ash -F #TODO login 
    #command: telnetd -F
    mac_address: a0:ab:1b:7c:8b:48
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      iot_network:
        ipv4_address: 172.16.238.50

  cam1:
    container_name: dl-cam1
    image: tesi
    volumes:
      - /home/simone/volume_tesi:/home/root/test_files
      - /home/simone/volume_tesi/lighttpd:/opt/lighttpd
      - /home/simone/volume_tesi/lighttpd_www/:/var/www
      - /home/simone/volume_tesi/lighttpd_ssl/:/var/ssl
    command: /home/root/test_files/start.sh #telnetd -l /bin/ash -F 
      # lighttpd -D -f /opt/lighttpd/lighttpd.conf
    mac_address: b2:c5:54:44:0f:a4
    cap_add:
      - NET_ADMIN
      - SYS_MODULE

    networks:
      iot_network:
        ipv4_address: 172.16.238.51



networks:
  iot_network:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"

