FROM ubuntu:22.04

RUN  apt-get update && apt-get install -y mysql-server mysql-client tar electric-fence libc6-dev nmap tcpdump iputils-ping python3 git build-essential netcat curl libssl-dev
RUN apt-get update && apt-get install -y python2.7

#go installation
RUN curl https://dl.google.com/go/go1.20.5.linux-amd64.tar.gz > /tmp/go.tar.gz
RUN tar -xf /tmp/go.tar.gz -C /usr/local
RUN echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc

COPY attack_tools /tools

#Get sfuzz:
#RUN mkdir tools ; cd tools ; git clone https://gitlab.com/kalilinux/packages/sfuzz 
#fixing a bug & build
RUN cd /tools/sfuzz ; chmod +x configure && ./configure --cc=gcc --enable-plugin-samples && make

#Get and build thc-ssl-dos:
#RUN apt-get update && apt-get install -y libssl-dev
RUN cd /tools/thc-ssl-dos && ./configure && make all

#Get saddam - remember to use in python 2.7
RUN curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output /tmp/get-pip.py ; python2.7 /tmp/get-pip.py ; python2.7 -m pip install virtualenv
RUN cd /tools/Saddam-new ; python2.7 -m virtualenv .

#Get bashlite
#RUN cd /tools ; git clone https://github.com/ifding/iot-malware
