FROM ubuntu:jammy

RUN apt-get update && apt-get install build-essential perl autoconf automake libtool autogen libopts25 -y

COPY udp_tools/ntp-4.2.6p5 /src

RUN cd /src && ./configure --disable-local-libopts --disable-libopts-install && make && make install

