version: '3'
services:
  homehub:
    container_name: dl-homehub
    image: victim
    volumes:
      - ./victim_tools/lighttpd/config:/opt/lighttpd
      - ./victim_tools/lighttpd/www/:/var/www
      - ./victim_tools/lighttpd/ssl/:/var/ssl
    command: /start.sh  
    mac_address: a0:ab:1b:7c:8b:48

    networks:
      iot_network:
        ipv4_address: 172.16.238.50

  cam1:
    container_name: dl-cam1
    image: victim
    volumes:
      - ./victim_tools/lighttpd/config:/opt/lighttpd
      - ./victim_tools/lighttpd/www/:/var/www
      - ./victim_tools/lighttpd/ssl/:/var/ssl
    command: /start.sh  
    mac_address: b2:c5:54:44:0f:a4

    networks:
      iot_network:
        ipv4_address: 172.16.238.51



networks:
  iot_network:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"

